(setq custom-file "~/.emacs.custom.el")
(setq inhibit-startup-message t)
(setq ring-bell-function 'ignore)
(setq backup-directory-alist '((".*" . "~/.emacs.d/backups/")))
(setq auto-save-file-name-transforms '((".*" "~/.emacs.d/auto-saves/" t)))
(setq auto-save-list-file-prefix "~/.emacs.d/auto-saves/.saves-")
(menu-bar-mode 0)
(tool-bar-mode 0)
(scroll-bar-mode 0)
(global-display-line-numbers-mode)
(set-frame-font "MonoLisa 15" nil t)
(add-to-list 'default-frame-alist '(fullscreen . maximized))
(load-file custom-file)
